def sharedPods
  pod 'Capable', '~> 0.9.0'
end

target 'Example-iOS' do
  platform :ios, '11.0'
  use_frameworks!

  sharedPods
  pod 'SheetyColors'
  pod 'AppCenter/Analytics'
  pod 'Fabric'
  pod 'Answers'
  pod 'Firebase/Core'
end

target 'Example-macOS' do
  platform :osx, '10.12'
  use_frameworks!

  sharedPods
end

target 'Example-tvOS' do
  platform :tvos, '10.0'
  use_frameworks!

  sharedPods
end

target 'Example-watchOS' do
  platform :watchos, '4.0'
  use_frameworks!
end

target 'Example-watchOS Extension' do
  platform :watchos, '4.0'
  use_frameworks!

  sharedPods
end
